<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>SariaShop</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.0.11" />
    <PackageReference Include="SPTarkov.DI" Version="4.0.11" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <PropertyGroup>
      <_ModOut>$(ProjectDir)Build/SPT/user/mods/Saria</_ModOut>
    </PropertyGroup>
    <MakeDir Directories="$(_ModOut)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(_ModOut)" />
    <Copy SourceFiles="$(ProjectDir)config.json" DestinationFolder="$(_ModOut)" />
    <ItemGroup>
      <_AssetFiles Include="$(ProjectDir)Assets/**/*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(_AssetFiles)" DestinationFolder="$(_ModOut)/Assets/%(RecursiveDir)" />
  </Target>
</Project>
